tag_icon_list:
  default: "tag1,question-circle,#CC0000|"
  type: "list"
  description: 'Enter comma-delimited configuration for tags, in the format "category-slug,icon,iconColor". (Icon color is optional.)'
svg_icons:
  default: "question-circle"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in this theme component"
tag_icon_fallback:
  default: ""
  description: 'Enter the icon for all other tags in the format "icon,iconColor". (Icon color is optional.)'
